
## other inputs: "s3", "etcd", "dynamo", "s3Express", "Aurora"
data_store: "dynamo"
aws_acc_id: 133132736141
region: us-east-1
# Sacheen acc =133132736141
# My acc = 471112959817
key:
  num: "1"
  size_start: "10" #bytes
  size_end: "31" #bytes
  jumps: "10" 
  sizes_list: "[93]"

value:
  size: "889" #bytes
  
num_readers: "1"

num_iters: "50" # to be sent to intial-lmd

# write code to verify and error check config inputs