
## other inputs: "etcd", "dynamodb", "s3Express", "Aurora"
data_store: "s3"
aws_acc_id: 471112959817

key:
  num: "1"
  size_start: "10" #bytes
  size_end: "20" #bytes
  jumps: "2" 

value:
  size: "100" #bytes
  
num_readers: "1"

num_iters: "5"
