
## other inputs: "s3", "etcd", "dynamo", "aurora"
data_store: "dynamo"
aws_acc_id: 133132736141
region: us-east-1
# Sacheen acc =133132736141
# My acc = 471112959817
key:
  num: "1"
  size_start: "10" #bytes
  size_end: "31" #bytes
  jumps: "10" 
  sizes_list: "[59]"

value:
  size: "889" #bytes
  
num_readers: "1"

num_iters: "200" # to be sent to intial-lmd

validation_run: "yes" # Set to yes for a validation run
# write code to verify and error check config inputs