
## other inputs: "s3", "etcd", "dynamo", "s3Express", "Aurora"
data_store: "dynamo"
aws_acc_id: 133132736141
region: us-east-1
# Sacheen acc =133132736141
# My acc = 471112959817
key:
  num: "1"
  size_start: "10" #bytes
  size_end: "20" #bytes
  jumps: "4" 

value:
  size: "100" #bytes
  
num_readers: "1"

num_iters: "5"

# write code to verify and error check config inputs